import { Elysia, t } from '../src'

const a0 = new Elysia().get('/a0', () => 'a')
const a1 = new Elysia().get('/a1', () => 'a')
const a2 = new Elysia().get('/a2', () => 'a')
const a3 = new Elysia().get('/a3', () => 'a')
const a4 = new Elysia().get('/a4', () => 'a')
const a5 = new Elysia().get('/a5', () => 'a')
const a6 = new Elysia().get('/a6', () => 'a')
const a7 = new Elysia().get('/a7', () => 'a')
const a8 = new Elysia().get('/a8', () => 'a')
const a9 = new Elysia().get('/a9', () => 'a')
const a10 = new Elysia().get('/a10', () => 'a')
const a11 = new Elysia().get('/a11', () => 'a')
const a12 = new Elysia().get('/a12', () => 'a')
const a13 = new Elysia().get('/a13', () => 'a')
const a14 = new Elysia().get('/a14', () => 'a')
const a15 = new Elysia().get('/a15', () => 'a')
const a16 = new Elysia().get('/a16', () => 'a')
const a17 = new Elysia().get('/a17', () => 'a')
const a18 = new Elysia().get('/a18', () => 'a')
const a19 = new Elysia().get('/a19', () => 'a')
const a20 = new Elysia().get('/a20', () => 'a')
const a21 = new Elysia().get('/a21', () => 'a')
const a22 = new Elysia().get('/a22', () => 'a')
const a23 = new Elysia().get('/a23', () => 'a')
const a24 = new Elysia().get('/a24', () => 'a')
const a25 = new Elysia().get('/a25', () => 'a')
const a26 = new Elysia().get('/a26', () => 'a')
const a27 = new Elysia().get('/a27', () => 'a')
const a28 = new Elysia().get('/a28', () => 'a')
const a29 = new Elysia().get('/a29', () => 'a')
const a30 = new Elysia().get('/a30', () => 'a')
const a31 = new Elysia().get('/a31', () => 'a')
const a32 = new Elysia().get('/a32', () => 'a')
const a33 = new Elysia().get('/a33', () => 'a')
const a34 = new Elysia().get('/a34', () => 'a')
const a35 = new Elysia().get('/a35', () => 'a')
const a36 = new Elysia().get('/a36', () => 'a')
const a37 = new Elysia().get('/a37', () => 'a')
const a38 = new Elysia().get('/a38', () => 'a')
const a39 = new Elysia().get('/a39', () => 'a')
const a40 = new Elysia().get('/a40', () => 'a')
const a41 = new Elysia().get('/a41', () => 'a')
const a42 = new Elysia().get('/a42', () => 'a')
const a43 = new Elysia().get('/a43', () => 'a')
const a44 = new Elysia().get('/a44', () => 'a')
const a45 = new Elysia().get('/a45', () => 'a')
const a46 = new Elysia().get('/a46', () => 'a')
const a47 = new Elysia().get('/a47', () => 'a')
const a48 = new Elysia().get('/a48', () => 'a')
const a49 = new Elysia().get('/a49', () => 'a')
const a50 = new Elysia().get('/a50', () => 'a')
const a51 = new Elysia().get('/a51', () => 'a')
const a52 = new Elysia().get('/a52', () => 'a')
const a53 = new Elysia().get('/a53', () => 'a')
const a54 = new Elysia().get('/a54', () => 'a')
const a55 = new Elysia().get('/a55', () => 'a')
const a56 = new Elysia().get('/a56', () => 'a')
const a57 = new Elysia().get('/a57', () => 'a')
const a58 = new Elysia().get('/a58', () => 'a')
const a59 = new Elysia().get('/a59', () => 'a')
const a60 = new Elysia().get('/a60', () => 'a')
const a61 = new Elysia().get('/a61', () => 'a')
const a62 = new Elysia().get('/a62', () => 'a')
const a63 = new Elysia().get('/a63', () => 'a')
const a64 = new Elysia().get('/a64', () => 'a')
const a65 = new Elysia().get('/a65', () => 'a')
const a66 = new Elysia().get('/a66', () => 'a')
const a67 = new Elysia().get('/a67', () => 'a')
const a68 = new Elysia().get('/a68', () => 'a')
const a69 = new Elysia().get('/a69', () => 'a')
const a70 = new Elysia().get('/a70', () => 'a')
const a71 = new Elysia().get('/a71', () => 'a')
const a72 = new Elysia().get('/a72', () => 'a')
const a73 = new Elysia().get('/a73', () => 'a')
const a74 = new Elysia().get('/a74', () => 'a')
const a75 = new Elysia().get('/a75', () => 'a')
const a76 = new Elysia().get('/a76', () => 'a')
const a77 = new Elysia().get('/a77', () => 'a')
const a78 = new Elysia().get('/a78', () => 'a')
const a79 = new Elysia().get('/a79', () => 'a')
const a80 = new Elysia().get('/a80', () => 'a')
const a81 = new Elysia().get('/a81', () => 'a')
const a82 = new Elysia().get('/a82', () => 'a')
const a83 = new Elysia().get('/a83', () => 'a')
const a84 = new Elysia().get('/a84', () => 'a')
const a85 = new Elysia().get('/a85', () => 'a')
const a86 = new Elysia().get('/a86', () => 'a')
const a87 = new Elysia().get('/a87', () => 'a')
const a88 = new Elysia().get('/a88', () => 'a')
const a89 = new Elysia().get('/a89', () => 'a')
const a90 = new Elysia().get('/a90', () => 'a')
const a91 = new Elysia().get('/a91', () => 'a')
const a92 = new Elysia().get('/a92', () => 'a')
const a93 = new Elysia().get('/a93', () => 'a')
const a94 = new Elysia().get('/a94', () => 'a')
const a95 = new Elysia().get('/a95', () => 'a')
const a96 = new Elysia().get('/a96', () => 'a')
const a97 = new Elysia().get('/a97', () => 'a')
const a98 = new Elysia().get('/a98', () => 'a')
const a99 = new Elysia().get('/a99', () => 'a')

const app1 = new Elysia()
	.use(a0)
	.use(a1)
	.use(a2)
	.use(a3)
	.use(a4)
	.use(a5)
	.use(a6)
	.use(a7)
	.use(a8)
	.use(a9)
	.use(a10)
	.use(a11)
	.use(a12)
	.use(a13)
	.use(a14)
	.use(a15)
	.use(a16)
	.use(a17)
	.use(a18)
	.use(a19)
	.use(a20)
	.use(a21)
	.use(a22)
	.use(a23)
	.use(a24)
	.use(a25)
	.use(a26)
	.use(a27)
	.use(a28)
	.use(a29)
	.use(a30)
	.use(a31)
	.use(a32)
	.use(a33)
	.use(a34)
	.use(a35)
	.use(a36)
	.use(a37)
	.use(a38)
	.use(a39)
	.use(a40)

const app2 = new Elysia()
	.use(a41)
	.use(a42)
	.use(a43)
	.use(a44)
	.use(a45)
	.use(a46)
	.use(a47)
	.use(a48)
	.use(a49)
	.use(a50)
	.use(a51)
	.use(a52)
	.use(a53)
	.use(a54)
	.use(a55)
	.use(a56)
	.use(a57)
	.use(a58)
	.use(a59)
	.use(a60)
	.use(a61)
	.use(a62)
	.use(a63)
	.use(a64)
	.use(a65)
	.use(a66)
	.use(a67)
	.use(a68)
	.use(a69)
	.use(a70)
	.use(a71)
	.use(a72)
	.use(a73)
	.use(a74)
	.use(a75)
	.use(a76)
	.use(a77)
	.use(a78)
	.use(a79)

const app3 = new Elysia()
	.use(a80)
	.use(a81)
	.use(a82)
	.use(a83)
	.use(a84)
	.use(a85)
	.use(a86)
	.use(a87)
	.use(a88)
	.use(a89)
	.use(a90)
	.use(a91)
	.use(a92)
	.use(a93)
	.use(a94)
	.use(a95)
	.use(a96)
	.use(a97)
	.use(a98)
	.use(a99)

const main = new Elysia().use(app1).use(app2).use(app3)
