import type { AnyElysia } from '../base'
import {
	endValidatorCapture,
	endHandlerCapture,
	checkFactorySource,
	mirrorFactorySource,
	handlerFactorySource,
	isValidatorCapturing,
	type CapturedValidator,
	type CapturedHandler
} from '../compile/aot'
import { env } from '../universal'
import { nullObject } from '../utils'

export interface CompileToSourceOptions {
	/** Emit a self-registering module (`Compiled.registerValidators(...)`). */
	register?: boolean

	// @internal
	registerFrom?: string
}

export async function compileToSource(
	app: AnyElysia,
	options?: CompileToSourceOptions
): Promise<string> {
	env.ELYSIA_AOT_BUILD = '1'

	if (!isValidatorCapturing())
		throw new Error(
			'[elysia-aot]: ELYSIA_AOT_BUILD=1 must be set to enable AOT capture mode'
		)

	const modules = (app as { modules?: Promise<unknown> }).modules
	if (modules) await modules
	;(app as { compile(): unknown }).compile()

	return emitModule(endValidatorCapture(), endHandlerCapture(), options)
}

function emitModule(
	captured: CapturedValidator[],
	handlers: CapturedHandler[],
	options?: CompileToSourceOptions
): string {
	// dedup source code
	const factoryRef = new Map<string, string>()

	// Codec branch-checks (the Numeric/Date/… `u` entries) are universal
	// boilerplate
	//
	// inline into every codec-bearing entry. Hoist them to
	// shared `_b` const so each is shipped
	const branchRef = new Map<string, string>()
	let branchDecls = ''
	let decls = ''

	const tree = nullObject() as Record<
		string,
		Record<string, Record<string, string>>
	>

	for (const c of captured) {
		const parts: string[] = []
		if (c.code) {
			parts.push(`c: ${checkFactorySource(c.identifier!, c.code)}`)

			if (c.external) parts.push('e:1')
			if (c.async) parts.push('a:1')
			if (c.hasDefault) parts.push('d:1')
			if (c.hasCodec) parts.push('k:1')
			if (c.hasRef) parts.push('r:1')
		}

		if (c.mirror) {
			const m = c.mirror
			let ms = `s: ${mirrorFactorySource(m.source, m.hasExternals)}`

			if (m.u)
				ms +=
					', u: [' +
					m.u
						.map(
							(branch) =>
								'[' +
								branch
									.map((b) => {
										const src = checkFactorySource(
											b.identifier,
											b.code
										)

										let ref = branchRef.get(src)
										if (ref === undefined) {
											ref = `_b${branchRef.size}`
											branchRef.set(src, ref)
											branchDecls += `const ${ref} = ${src}\n`
										}

										return ref
									})
									.join(', ') +
								']'
						)
						.join(', ') +
					']'

			parts.push(`m: { ${ms} }`)
		}

		if (!parts.length) continue

		const entrySrc = `{ ${parts.join(', ')} }`
		let ref = factoryRef.get(entrySrc)

		if (ref === undefined) {
			ref = `_c${factoryRef.size}`
			factoryRef.set(entrySrc, ref)
			decls += `const ${ref} = ${entrySrc}\n`
		}

		const byPath = (tree[c.method] ??= nullObject() as any)
		const bySlot = (byPath[c.path] ??= nullObject() as any)

		bySlot[c.slot] = ref
	}

	// dedup handler by source
	const handlerRef = new Map<string, string>()
	let handlerDecls = ''
	const handlerTree = nullObject() as Record<string, Record<string, string>>

	for (const h of handlers) {
		const src = handlerFactorySource(h.alias, h.code)

		let ref = handlerRef.get(src)
		if (ref === undefined) {
			ref = `_h${handlerRef.size}`
			handlerRef.set(src, ref)
			handlerDecls += `const ${ref} = ${src}\n`
		}

		;(handlerTree[h.method] ??= {})[h.path] =
			`{ a: ${JSON.stringify(h.alias)}, f: ${ref} }`
	}

	let body = '// Generated by Elysia build plugin. Do not edit.\n'

	if (options?.register)
		body += `import { Compiled } from ${JSON.stringify(
			options.registerFrom ?? 'elysia'
		)}\n`

	body +=
		'\n' +
		branchDecls +
		(branchDecls && '\n') +
		decls +
		handlerDecls +
		'\nexport const validators = {\n'

	for (const method in tree) {
		body += `\t${JSON.stringify(method)}: {\n`
		for (const path in tree[method]) {
			const slots = Object.entries(tree[method]![path]!)
				.map(([slot, ref]) => `${JSON.stringify(slot)}: ${ref}`)
				.join(', ')

			body += `\t\t${JSON.stringify(path)}: { ${slots} },\n`
		}

		body += '\t},\n'
	}

	body += '}\n'

	body += '\nexport const handlers = {\n'
	for (const method in handlerTree) {
		body += `\t${JSON.stringify(method)}: {\n`
		for (const path in handlerTree[method])
			body += `\t\t${JSON.stringify(path)}: ${handlerTree[method]![path]},\n`
		body += '\t},\n'
	}

	body += '}\n'

	if (options?.register) {
		body += '\nCompiled.validators = validators\n'
		body += 'Compiled.handlers = handlers\n'
	}

	body += '\nexport default validators\n'

	return body
}
