name: 🚀 Feature Request
description: Suggest an idea, feature, or enhancement
labels: [enhancement]
body:
    - type: markdown
      attributes:
          value: |
              Thank you for submitting a bug report

              If want a chat or discussion first then let's talk in [Discord](https://discord.com/invite/eaFJ2KDJck)

              Please try to include as much information as possible.

    - type: textarea
      attributes:
          label: What is the problem this feature would solve?
      validations:
          required: true

    - type: textarea
      attributes:
          label: What is the feature you are proposing to solve the problem?
      validations:
          required: true

    - type: textarea
      attributes:
          label: What alternatives have you considered?
