import '../../src/compile/aot-capture' // installs captureImpl
import { describe, it, expect, afterEach } from 'bun:test'
import { Elysia, t } from '../../src'
import { Validator } from '../../src/validator'
import { Compiled, Capture } from '../../src/compile/aot'
import { endValidatorCapture } from '../../src/compile/aot-capture'
import { captureArtifacts } from '../../src/plugin/aot/source'

afterEach(() => {
	Compiled.clear()
	Validator.clear()
	// Drain shared capture state even when a test fails early.
	try {
		endValidatorCapture()
	} catch {}
})

describe('capture cleanup', () => {
	it('leaves capture inactive after a failed build', async () => {
		const bad = new Elysia()
			.model('user', undefined as any) // deliberately broken model
			.get('/', { response: 'user' }, () => 'ok')

		await expect(captureArtifacts(bad as any)).rejects.toThrow()

		expect(Capture.isCapturing()).toBe(false)
	})

	it('allows a subsequent capture after a failure', async () => {
		const bad = new Elysia()
			.model('user', undefined as any)
			.get('/', { response: 'user' }, () => 'ok')

		await expect(captureArtifacts(bad as any)).rejects.toThrow()

		const good = new Elysia().get('/ok', () => 'ok')
		const result = await captureArtifacts(good as any)
		expect(result.source).toContain('Generated by Elysia')
	})

	it('fails clearly after strict production retention sealing', async () => {
		const previous = process.env.NODE_ENV
		try {
			process.env.NODE_ENV = 'production'
			const app = new Elysia().get('/ok', () => 'ok').compile()
			expect(app['~generation']?.plan).toBeUndefined()
			await expect(captureArtifacts(app as any)).rejects.toThrow(
				'AppPlan unavailable after production retention sealing'
			)
		} finally {
			if (previous === undefined) delete process.env.NODE_ENV
			else process.env.NODE_ENV = previous
		}
	})

	it('rejects an app compiled before validator capture begins', async () => {
		const previous = process.env.NODE_ENV
		try {
			process.env.NODE_ENV = 'development'
			const app = new Elysia()
				.get('/ok', () => 'ok', { query: t.Object({ id: t.Number() }) })
				.compile()
			await expect(
				captureArtifacts(app as any, { target: 'bun', register: true })
			).rejects.toThrow('Capture must begin before app compilation')
		} finally {
			if (previous === undefined) delete process.env.NODE_ENV
			else process.env.NODE_ENV = previous
		}
	})

	it('allows only one concurrent capture session', async () => {
		const appA = new Elysia().get('/a', () => 'a')
		const appB = new Elysia().get('/b', () => 'b')

		const [resultA, resultB] = await Promise.allSettled([
			captureArtifacts(appA as any),
			captureArtifacts(appB as any)
		])

		const rejected = [resultA, resultB].filter(
			(r) => r.status === 'rejected'
		)
		const fulfilled = [resultA, resultB].filter(
			(r) => r.status === 'fulfilled'
		)

		expect(rejected.length).toBe(1)
		expect(fulfilled.length).toBe(1)

		const err = (rejected[0] as PromiseRejectedResult).reason
		expect(err?.message ?? String(err)).toContain('already active')

		expect(Capture.isCapturing()).toBe(false)
	})
})
