/**
 * H09: AOT capture state is non-transactional and non-reentrant.
 *
 * Tests:
 * 1. A failed capture (route with missing model) leaves isCapturing()=false
 *    and both capture maps empty so a subsequent sequential capture works.
 * 2. Concurrent captureArtifacts calls are rejected with a clear error (instead
 *    of the second silently overwriting the first's capture maps).
 */
import '../../src/compile/aot-capture' // installs captureImpl
import { describe, it, expect, afterEach } from 'bun:test'
import { Elysia } from '../../src'
import { Validator } from '../../src/validator'
import { Compiled, Capture, endValidatorCapture, endHandlerCapture } from '../../src/compile/aot'
import { captureArtifacts } from '../../src/plugin/aot/source'

afterEach(() => {
	Compiled.clear()
	Validator.clear()
	// Drain any leftover capture that a test may have leaked via beginValidatorCapture
	try { endValidatorCapture() } catch {}
	try { endHandlerCapture() } catch {}
})

describe('H09 — capture cleanup', () => {
	it('leaves isCapturing()=false and empty maps after a failed capture', async () => {
		// An app referencing an undeclared model should throw during compile.
		const bad = new Elysia()
			.model('user', undefined as any) // deliberately broken model
			.get('/', { response: 'user' }, () => 'ok')

		await expect(captureArtifacts(bad as any)).rejects.toThrow()

		// After the failure, capture state must be fully cleaned up.
		expect(Capture.isCapturing()).toBe(false)
	})

	it('a second sequential captureArtifacts works after a failed first one', async () => {
		// Fail once — this used to leave the maps populated.
		const bad = new Elysia()
			.model('user', undefined as any)
			.get('/', { response: 'user' }, () => 'ok')

		await expect(captureArtifacts(bad as any)).rejects.toThrow()

		// A clean second capture should succeed.
		const good = new Elysia().get('/ok', () => 'ok')
		const result = await captureArtifacts(good as any)
		expect(result.source).toContain('Generated by Elysia')
	})

	it('concurrent captureArtifacts rejects with a clear error', async () => {
		// Two concurrent captures. The second beginValidatorCapture should throw
		// because the first session is already active.
		const appA = new Elysia().get('/a', () => 'a')
		const appB = new Elysia().get('/b', () => 'b')

		const [resultA, resultB] = await Promise.allSettled([
			captureArtifacts(appA as any),
			captureArtifacts(appB as any)
		])

		// Exactly one should succeed; the other should reject with the
		// concurrent-session error.
		const rejected = [resultA, resultB].filter((r) => r.status === 'rejected')
		const fulfilled = [resultA, resultB].filter(
			(r) => r.status === 'fulfilled'
		)

		expect(rejected.length).toBe(1)
		expect(fulfilled.length).toBe(1)

		const err = (rejected[0] as PromiseRejectedResult).reason
		expect(err?.message ?? String(err)).toContain('already active')

		// After both settle, capture state must be clean.
		expect(Capture.isCapturing()).toBe(false)
	})
})
