import '../../src/compile/aot-capture' // installs captureImpl
import { describe, it, expect, afterEach } from 'bun:test'
import { Elysia } from '../../src'
import { Validator } from '../../src/validator'
import { Compiled, Capture } from '../../src/compile/aot'
import {
	endValidatorCapture,
	endHandlerCapture
} from '../../src/compile/aot-capture'
import { captureArtifacts } from '../../src/plugin/aot/source'

afterEach(() => {
	Compiled.clear()
	Validator.clear()
	// Drain shared capture state even when a test fails early.
	try {
		endValidatorCapture()
	} catch {}
	try {
		endHandlerCapture()
	} catch {}
})

describe('capture cleanup', () => {
	it('leaves capture inactive after a failed build', async () => {
		const bad = new Elysia()
			.model('user', undefined as any) // deliberately broken model
			.get('/', { response: 'user' }, () => 'ok')

		await expect(captureArtifacts(bad as any)).rejects.toThrow()

		expect(Capture.isCapturing()).toBe(false)
	})

	it('allows a subsequent capture after a failure', async () => {
		const bad = new Elysia()
			.model('user', undefined as any)
			.get('/', { response: 'user' }, () => 'ok')

		await expect(captureArtifacts(bad as any)).rejects.toThrow()

		const good = new Elysia().get('/ok', () => 'ok')
		const result = await captureArtifacts(good as any)
		expect(result.source).toContain('Generated by Elysia')
	})

	it('allows only one concurrent capture session', async () => {
		const appA = new Elysia().get('/a', () => 'a')
		const appB = new Elysia().get('/b', () => 'b')

		const [resultA, resultB] = await Promise.allSettled([
			captureArtifacts(appA as any),
			captureArtifacts(appB as any)
		])

		const rejected = [resultA, resultB].filter(
			(r) => r.status === 'rejected'
		)
		const fulfilled = [resultA, resultB].filter(
			(r) => r.status === 'fulfilled'
		)

		expect(rejected.length).toBe(1)
		expect(fulfilled.length).toBe(1)

		const err = (rejected[0] as PromiseRejectedResult).reason
		expect(err?.message ?? String(err)).toContain('already active')

		expect(Capture.isCapturing()).toBe(false)
	})
})
