import type {
	ValidatorManifest,
	HandlerManifest,
	WSRouteManifest
} from './compile/aot'

/**
 * Stub for the `elysia/compiled` import.
 *
 * A build plugin (`elysia/plugin/*`) redirects this specifier to a module
 * generated by `compileToSource`, which self-registers the frozen validator +
 * handler manifest. Without a plugin it resolves here and is a harmless no-op.
 * Named exports mirror what `compileToSource` emits.
 *
 * @see compileToSource
 */
export const validators: ValidatorManifest | undefined = undefined
export const handlers: HandlerManifest | undefined = undefined
export const wsRoutes: WSRouteManifest | undefined = undefined

export default validators
