import type {
	AppPlanAotPayload,
	AppPlanAotValidatorManifest,
	AppPlanAotWSManifest
} from './compile/app-plan-aot'

/**
 * Stub for the `elysia/compiled` import.
 *
 * A build plugin (`elysia/plugin/*`) redirects this specifier to a module
 * generated by `compileToSource`, which self-registers the AppPlan image.
 * Without a plugin it resolves here and is a harmless no-op.
 * Named exports mirror what `compileToSource` emits.
 *
 * @see compileToSource
 */
export const appPlanValidators: AppPlanAotValidatorManifest | undefined =
	undefined
export const appPlanWSRoutes: AppPlanAotWSManifest | undefined = undefined
export const appPlanPayload: AppPlanAotPayload | undefined = undefined

export default appPlanValidators
